packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - necord

onlyBuiltDependencies:
  - '@discordjs/opus'
  - '@nestjs/core'
  - '@suites/di.nestjs'
  - '@suites/doubles.vitest'
  - '@swc/core'
  - esbuild
  - unrs-resolver
  - zeromq
