packages:
  - apps/*
  - packages/*

allowBuilds:
  '@discordjs/opus': true
  '@nestjs/core': true
  '@suites/di.nestjs': true
  '@suites/doubles.vitest': true
  '@swc/core': true
  necord: true
  unrs-resolver: true
